version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ldap_user_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        LDAP_CA_CERT: ${LDAP_CA_CERT}
    container_name: ldap_client
    ports:
      - "2222:2222"
    environment:
      LDAP_BASE: dc=mieweb,dc=com
      LDAP_URI: ldaps://host.docker.internal:636
      LDAP_ADMIN_DN: cn=admin,dc=mieweb,dc=com
      LDAP_ADMIN_PW: secret
      LDAP_DOMAIN: mieweb.com
      LDAP_ORG: "MIE Organization"
      LDAP_CERT_SUBJ: "/C=US/ST=IN/L=FW/O=MIE/OU=OrgUnit/CN=mieweb.com"
      SSH_PORT: 2222
      LDAP_CA_CERT: ${LDAP_CA_CERT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
