services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1390:1390"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=ldap_user_db
      - LDAP_PORT=1390
      - LDAP_BASE_DN=dc=mieweb,dc=com
      - LDAP_ADMIN_DN=cn=admin,dc=mieweb,dc=com
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - ./server:/usr/src/app
      - ./ssl:/usr/src/app/ssl
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ldap_user_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ldap_client
    environment: 
      - LDAP_BASE = dc=mieweb, dc=com
      - LDAP_URI = ldaps://app:1390
      - LDAP_ADMIN_DN = cn=admin, dc=mieweb, dc=com
      - LDAP_ADMIN_PW = secret
      - LDAP_DOMAIN = mieweb.com
      - LDAP_ORG = "MIE Organization"
      - LDAP_CERT_SUBJ = "/C=US/ST=IN/L=FW/O=MIE/OU=OrgUnit/CN=mieweb.com"
      - SSH_PORT = 2222
    ports:
      - "2222:2222"
    volumes:
      - ./client:/etc/client
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: