version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ldap_user_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ldap_client
    ports:
      - "2222:2222"
    env_file:
      - ./client/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
